server:
  port: 9999
  context-path: /springboot-aop
  jsp-servlet:
    init-parameters:
      development: true


spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
    encoding:
      charset: utf-8
      force: true